{ ... }:
{
  imports = [
    ./bash.nix
    ./bashrc-personal.nix
    ./bat.nix
    ./btop.nix
    ./broot.nix
    ./cava.nix
    ./dms.nix
    ./emoji.nix
    ./eza.nix
    ./fish
    ./foot.nix
    ./fzf.nix
    ./git.nix
    ./gtk.nix
    ./helix.nix
    ./lazygit.nix
    ./niri
    ./obsidian.nix
    ./obs-studio.nix
    ./qt.nix
    ./scripts
    ./starship.nix
    ./swappy.nix
    ./tealdeer.nix
    ./xdg.nix
    ./yazi.nix
    ./yazi-picker.nix
    ./zoxide.nix
    ./environment.nix
    ./zellij
    ./zen.nix
  ];
}
